<a href="https://colab.research.google.com/github/riyawakde16-art/Day23/blob/main/Day23.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import files
uploaded=files.upload()

Saving Colth.csv to Colth.csv


In [ ]:
filepath="/content/Colth.csv"
data=pd.read_csv(filepath)

Q.1.

In [ ]:
# Preprocessing
data = data.dropna()
data = pd.get_dummies(data, drop_first=True)

In [ ]:
# Assume last column is target (change if needed)
X = data.iloc[:, :-1]
y = data.iloc[:, -1]

In [ ]:
# Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [ ]:
# Model
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [ ]:
# Prediction
y_pred = model.predict(X_test)

In [ ]:
# Evaluation
print("R2 Score:", r2_score(y_test, y_pred))

R2 Score: 0.33241771444306933


In [ ]:
print("Predictions:", y_pred[:5])

Predictions: [-0.08971008  0.0191047   0.01000065  0.4417467  -0.01251538]


Q.2.

In [ ]:
# Split features & target
X = data.iloc[:, :-1]
y = data.iloc[:, -1]

In [ ]:
# Clean data
data = data.dropna()

In [ ]:
# Convert categorical → numeric
X = pd.get_dummies(X, drop_first=True)

In [ ]:
# Ensure target is numeric (0/1)
y = pd.factorize(y)[0]

In [ ]:
# Split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [ ]:

# scaling
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


In [ ]:
# Model
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [ ]:
# Prediction
y_pred = model.predict(X_test)

In [ ]:

from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred, average='macro'))
print("Recall:", recall_score(y_test, y_pred, average='macro'))
print("F1 Score:", f1_score(y_test, y_pred, average='macro'))

Confusion Matrix:
 [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Accuracy: 0.0
Precision: 0.0
Recall: 0.0
F1 Score: 0.0


/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


Q.3

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
k_values = [3, 5, 7]
results = {}
for k in k_values:
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train, y_train)
    y_pred = knn.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    results[k] = acc
    print(f"K={k}, Accuracy={acc}")

best_k = max(results, key=results.get)
print("Best K:", best_k)

K=3, Accuracy=0.0
K=5, Accuracy=0.0
K=7, Accuracy=0.0
Best K: 3


Q.4

In [ ]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import classification_report
nb = GaussianNB()
nb.fit(X_train, y_train)
y_pred = nb.predict(X_test)
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))

Confusion Matrix:
 [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Classification Report:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00       0.0
          10       0.00      0.00      0.00       0.0
          14       0.00      0.00      0.00       1.0
          17       0.00      0.00      0.00       0.0
          18       0.00      0.00      0.00       1.0
          19       0.00      0.00      0.00       0.0
          23       0.00      0.00      0.00       1.0
          25       0.00      0.00      0.00       0.0
          27       0.00      0.00      0.00       0.0
          31       0.00      0.00      0.00       1.0
          33       0.00      0.00      0.00       1.0
          34       0.00      0.00      0.00       0.0
          35       0.00      0.00      0.00       0.0
          37       0.00      0.00      0.00       1.0
          38       0.00   

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_

Q.5

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
import pandas as pd

# Logistic Regression
lr = LogisticRegression(max_iter=1000)
lr.fit(X_train, y_train)
lr_pred = lr.predict(X_test)

# KNN (Best k = 7)
knn = KNeighborsClassifier(n_neighbors=7)
knn.fit(X_train, y_train)
knn_pred = knn.predict(X_test)

# Naive Bayes
nb = GaussianNB()
nb.fit(X_train, y_train)
nb_pred = nb.predict(X_test)


In [ ]:
comparison = pd.DataFrame({
    "Algorithm": ["Logistic Regression", "KNN", "Naive Bayes"],

    "Accuracy": [
        accuracy_score(y_test, lr_pred),
        accuracy_score(y_test, knn_pred),
        accuracy_score(y_test, nb_pred)
    ],

    "Precision": [
        precision_score(y_test, lr_pred, average='weighted'),
        precision_score(y_test, knn_pred, average='weighted'),
        precision_score(y_test, nb_pred, average='weighted')
    ],

    "Recall": [
        recall_score(y_test, lr_pred, average='weighted'),
        recall_score(y_test, knn_pred, average='weighted'),
        recall_score(y_test, nb_pred, average='weighted')
    ],

    "F1 Score": [
        f1_score(y_test, lr_pred, average='weighted'),
        f1_score(y_test, knn_pred, average='weighted'),
        f1_score(y_test, nb_pred, average='weighted')
    ]
})

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/m

In [ ]:
print(comparison)

best = comparison.loc[comparison["Accuracy"].idxmax()]
print("\nBest Algorithm:", best["Algorithm"])
print("Reason: It has the highest Accuracy.")

             Algorithm  Accuracy  Precision  Recall  F1 Score
0  Logistic Regression       0.0        0.0     0.0       0.0
1                  KNN       0.0        0.0     0.0       0.0
2          Naive Bayes       0.0        0.0     0.0       0.0

Best Algorithm: Logistic Regression
Reason: It has the highest Accuracy.
