In [20]:
import numpy as np

arr = np.random.randn(6, 6)

print("Matrix:\n", arr)
print("Shape:", arr.shape)
print("Size:", arr.size)
print("Data Type:", arr.dtype)

print("Index of Maximum:", np.argmax(arr))
print("Index of Minimum:", np.argmin(arr))

print("\nTop-left 3x3 Submatrix:\n", arr[:3, :3])

arr = np.abs(arr)

print("\nModified Matrix:\n", arr)
print("Mean:", arr.mean())

Matrix:
 [[-1.53149077  2.0330501   1.93669812  1.51406935 -0.62024149  0.39265674]
 [-1.21815484 -0.51295751  0.35578591 -0.1196462  -0.49245879 -1.28399957]
 [-0.18741634 -2.12565426  0.31844416 -0.24900512  0.42359355 -1.49511527]
 [-1.25078764 -2.05492278  0.67138743  1.79612117  0.30636556  1.19883822]
 [-1.15337681 -0.91364593 -1.24808668 -0.7607885  -0.44080046 -0.82005204]
 [ 0.32957157  0.0283802  -0.09843621 -0.24256151  0.40463749  0.77421448]]
Shape: (6, 6)
Size: 36
Data Type: float64
Index of Maximum: 1
Index of Minimum: 13

Top-left 3x3 Submatrix:
 [[-1.53149077  2.0330501   1.93669812]
 [-1.21815484 -0.51295751  0.35578591]
 [-0.18741634 -2.12565426  0.31844416]]

Modified Matrix:
 [[1.53149077 2.0330501  1.93669812 1.51406935 0.62024149 0.39265674]
 [1.21815484 0.51295751 0.35578591 0.1196462  0.49245879 1.28399957]
 [0.18741634 2.12565426 0.31844416 0.24900512 0.42359355 1.49511527]
 [1.25078764 2.05492278 0.67138743 1.79612117 0.30636556 1.19883822]
 [1.15337681 0.913