In [16]:
import numpy as np

arr = np.array([[10, 20, 30, 40],
                [50, 60, 70, 80],
                [90, 100, 110, 120]])

print("Array:\n", arr)

print("\nFirst Row:", arr[0])
print("Last Column:", arr[:, -1])
print("Center 2x2 Submatrix:\n", arr[0:2, 1:3])
print("Even Numbers:", arr[arr % 2 == 0])

Array:
 [[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]

First Row: [10 20 30 40]
Last Column: [ 40  80 120]
Center 2x2 Submatrix:
 [[20 30]
 [60 70]]
Even Numbers: [ 10  20  30  40  50  60  70  80  90 100 110 120]
