In [19]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

print("Matrix A:\n", A)
print("Matrix B:\n", B)

# Element-wise Multiplication
print("\nElement-wise Multiplication:\n", A * B)

# Matrix Multiplication
print("\nMatrix Multiplication:\n", A @ B)

# Difference:
# * performs multiplication of corresponding elements.
# @ (or np.dot()) performs actual matrix multiplication.

Matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix B:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]

Element-wise Multiplication:
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]

Matrix Multiplication:
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
