In [15]:
import numpy as np

arr = np.arange(1, 25)

print("Original Array:\n", arr)
print("Shape:", arr.shape)

a = arr.reshape(4, 6)
print("\nReshape (4,6):")
print(a)
print("Shape:", a.shape)

b = arr.reshape(3, 8)
print("\nReshape (3,8):")
print(b)
print("Shape:", b.shape)

c = arr.reshape(2, 3, 4)
print("\nReshape (2,3,4):")
print(c)
print("Shape:", c.shape)

Original Array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
Shape: (24,)

Reshape (4,6):
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
Shape: (4, 6)

Reshape (3,8):
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]]
Shape: (3, 8)

Reshape (2,3,4):
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
Shape: (2, 3, 4)
