In [12]:
import numpy as np

arr = np.random.randint(10, 101, (5, 6))

print("Array:\n", arr)
print("Shape:", arr.shape)
print("Total Elements:", arr.size)
print("Data Type:", arr.dtype)

Array:
 [[64 75 56 83 45 85]
 [49 95 48 17 50 85]
 [48 15 94 38 93 31]
 [11 57 87 88 19 10]
 [73 39 88 56 32 98]]
Shape: (5, 6)
Total Elements: 30
Data Type: int64
