In [21]:
import numpy as np

# Generate marks for 10 students (5 subjects)
marks = np.random.randint(30, 101, (10, 5))

print("Student Marks:\n")
print(marks)

# Total and Average of each student
total = marks.sum(axis=1)
average = marks.mean(axis=1)

print("\nTotal Marks:")
print(total)

print("\nAverage Marks:")
print(average)

# Highest and Lowest scorer
highest = np.argmax(total)
lowest = np.argmin(total)

print("\nHighest Scoring Student Index:", highest)
print("Total Marks:", total[highest])

print("\nLowest Scoring Student Index:", lowest)
print("Total Marks:", total[lowest])

# Overall class statistics
print("\nClass Mean:", marks.mean())
print("Class Standard Deviation:", marks.std())

# Top 3 students
top3 = np.argsort(total)[-3:]

print("\nTop 3 Students Marks:")
print(marks[top3])

# Comments:
# sum(axis=1) -> Total marks of each student.
# mean(axis=1) -> Average marks of each student.
# argmax() -> Index of highest scorer.
# argmin() -> Index of lowest scorer.
# argsort()[-3:] -> Indices of top 3 students.

Student Marks:

[[99 65 62 37 54]
 [88 99 40 69 42]
 [97 47 59 96 31]
 [39 33 78 37 31]
 [94 96 52 56 99]
 [69 40 91 67 77]
 [94 59 70 77 60]
 [59 64 53 48 86]
 [37 65 54 63 32]
 [88 67 52 48 79]]

Total Marks:
[317 338 330 218 397 344 360 310 251 334]

Average Marks:
[63.4 67.6 66.  43.6 79.4 68.8 72.  62.  50.2 66.8]

Highest Scoring Student Index: 4
Total Marks: 397

Lowest Scoring Student Index: 3
Total Marks: 218

Class Mean: 63.98
Class Standard Deviation: 20.98712938922329

Top 3 Students Marks:
[[69 40 91 67 77]
 [94 59 70 77 60]
 [94 96 52 56 99]]
