In [14]:
import numpy as np

arr = np.random.randint(20, 81, (4, 5))

print("Matrix:\n", arr)
print("Minimum Value:", arr.min())
print("Maximum Value:", arr.max())
print("Sum:", arr.sum())
print("Mean:", arr.mean())
print("Standard Deviation:", arr.std())
print("Row Sum:", arr.sum(axis=1))
print("Column Sum:", arr.sum(axis=0))

Matrix:
 [[38 48 70 76 40]
 [74 32 50 68 52]
 [50 67 32 68 55]
 [43 30 78 48 31]]
Minimum Value: 30
Maximum Value: 78
Sum: 1050
Mean: 52.5
Standard Deviation: 15.790820118030602
Row Sum: [272 276 272 230]
Column Sum: [205 177 230 260 178]
