In [9]:
import numpy as np

# Create a 4x4 matrix of random integers
arr = np.random.randint(1, 101, (4, 4))

# Display array and its properties
print("4x4 Random Matrix:")
print(arr)

print("\nShape:", arr.shape)
print("Dimension:", arr.ndim)
print("Total Elements:", arr.size)
print("Data Type:", arr.dtype)

4x4 Random Matrix:
[[ 1 81  6 33]
 [29 78 57 24]
 [36 46 18 17]
 [68 84 80 53]]

Shape: (4, 4)
Dimension: 2
Total Elements: 16
Data Type: int64
