In [6]:
import numpy as np

# a) 1D array of 10 random numbers
arr1 = np.random.rand(10)

# b) 3x3 random matrix (standard normal distribution)
arr2 = np.random.randn(3, 3)

print("Random Array (0 to 1):")
print(arr1)

print("\n3x3 Random Matrix:")
print(arr2)

Random Array (0 to 1):
[0.76803196 0.30578162 0.2229719  0.15192859 0.13226785 0.84246018
 0.61363116 0.36430785 0.3712758  0.46879375]

3x3 Random Matrix:
[[ 0.60722532 -0.00552938  0.67526697]
 [ 0.66645464  1.28606278 -2.00891688]
 [ 0.73845998 -1.0207284   0.94125049]]
