In [7]:
import numpy as np

# Create vectors
v1 = np.array([2, 4, 6, 8])
v2 = np.array([1, 3, 5, 7])

# Operations
addition = v1 + v2
subtraction = v1 - v2
multiplication = v1 * v2
dot_product = np.dot(v1, v2)

# Display results
print("Vector 1:", v1)
print("Vector 2:", v2)

print("\nAddition:")
print(addition)

print("\nSubtraction:")
print(subtraction)

print("\nElement-wise Multiplication:")
print(multiplication)

print("\nDot Product:")
print(dot_product)

Vector 1: [2 4 6 8]
Vector 2: [1 3 5 7]

Addition:
[ 3  7 11 15]

Subtraction:
[1 1 1 1]

Element-wise Multiplication:
[ 2 12 30 56]

Dot Product:
100
