In [10]:
import numpy as np

# Generate 20 random integers between 1 and 50
arr = np.random.randint(1, 51, 20)

# Reshape into 4x5 matrix
matrix = arr.reshape(4, 5)

# Display matrix
print("4x5 Matrix:")
print(matrix)

# Statistics
print("\nSum:", np.sum(matrix))
print("Mean:", np.mean(matrix))
print("Standard Deviation:", np.std(matrix))

# Maximum value in each row
print("\nMaximum Value in Each Row:")
print(np.max(matrix, axis=1))

4x5 Matrix:
[[27 29 40 18 15]
 [ 3  2 29 23 20]
 [23 35 11 17 23]
 [14 45 21 50 35]]

Sum: 480
Mean: 24.0
Standard Deviation: 12.373358476985947

Maximum Value in Each Row:
[40 29 35 50]
