In [8]:
import numpy as np

# Create matrices
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

B = np.array([[9,8,7],
              [6,5,4],
              [3,2,1]])

# Operations
addition = A + B
matrix_multiplication = np.dot(A, B)
elementwise_multiplication = A * B

# Display results
print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

print("\nMatrix Addition:")
print(addition)

print("\nMatrix Multiplication:")
print(matrix_multiplication)

print("\nElement-wise Multiplication:")
print(elementwise_multiplication)

Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Matrix Addition:
[[10 10 10]
 [10 10 10]
 [10 10 10]]

Matrix Multiplication:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Element-wise Multiplication:
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]
