In [11]:
import numpy as np

try:
    # User input
    n = int(input("How many numbers do you want to generate? "))

    if n <= 0:
        print("Please enter a positive number.")

    else:
        # Generate random numbers
        arr = np.random.randint(10, 101, n)

        # Display array
        print("\nGenerated Array:")
        print(arr)

        # Statistics
        print("\nMean:", np.mean(arr))
        print("Median:", np.median(arr))
        print("Standard Deviation:", np.std(arr))
        print("Minimum:", np.min(arr))
        print("Maximum:", np.max(arr))

        # Reshape if possible
        if n % 2 == 0:
            matrix = arr.reshape(2, n // 2)
            print("\nReshaped 2D Array:")
            print(matrix)

            print("\nRow-wise Sum:")
            print(np.sum(matrix, axis=1))
        else:
            print("\nCannot reshape into a 2D array because the number of elements is odd.")

except ValueError:
    print("Invalid input! Please enter an integer.")

How many numbers do you want to generate? 10

Generated Array:
[91 61 13 28 73 82 46 94 17 98]

Mean: 60.3
Median: 67.0
Standard Deviation: 30.809251857193807
Minimum: 13
Maximum: 98

Reshaped 2D Array:
[[91 61 13 28 73]
 [82 46 94 17 98]]

Row-wise Sum:
[266 337]
