In [2]:
import numpy as np

arr = np.array([10,20,30,40,50])
# b) create a 2D arrray (3x3) using np.array()
ar=np.array([[1,2,3],[4,5,6]])

print("1D array")
print(arr)
print("shape :",arr.shape)
print("data type :",arr.dtype)

print("2D array")
print(ar)
print("shape :",ar.shape)
print("data type :",ar.dtype)

1D array
[10 20 30 40 50]
shape : (5,)
data type : int64
2D array
[[1 2 3]
 [4 5 6]]
shape : (2, 3)
data type : int64
